name = "ExtSrcImg"
authors = ["Ziyi Yin and Rafael Orozco"]

[deps]
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JOLI = "bb331ad6-a1cf-11e9-23da-9bcb53c69f6f"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
SetIntersectionProjection = "335f7d24-6316-57dd-9c3a-df470f2b739e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.5.0"
